[[entries]]
id = "c5cd1ad2-b903-4579-9157-6ec34cf00327"
type = "feature"
description = "Add `check_lockfile()` and `PythonBuildSystem.check_lockfile()` to check that the poetry.lock is compatible with pyproject.toml`"
author = "@LozzaTray"
pr = "https://github.com/kraken-build/kraken-std/pull/125"
