[[entries]]
id = "c35a9d23-2db1-4dd0-8e04-088931ee0c9c"
type = "breaking change"
description = "Updated .gitignore task to generate a comprehensive global .gitignore"
author = "luke.bax@talktalk.net"
pr = "https://github.com/kraken-build/kraken-std/pull/115"

[[entries]]
id = "97ce7edd-11b9-49cf-a54a-afa34de14173"
type = "improvement"
description = "Kraken now ensures that the `__version__` variable in Python source files that commonly contain it (e.g. `__init__.py`, `__about__.py`, `_version.py`) matches the version being published."
author = "szymon.gula@helsing.ai"
pr = "https://github.com/kraken-build/kraken-std/pull/108"

[[entries]]
id = "c0579eb5-e326-42dc-b50c-f9f3439163ee"
type = "fix"
description = "Fix: Python development versions are now released as `.post0.devN` instead of `.devN`, to order them behind the tag they're based on."
author = "@j-baker"
pr = "https://github.com/kraken-build/kraken-std/pull/98"

[[entries]]
id = "3abfd80c-20a5-4455-bb64-a33ed5209fac"
type = "improvement"
description = "Added a copyright task for calling pyaddlicense"
author = "michael.coward@helsing.ai"
pr = "https://github.com/kraken-build/kraken-std/pull/114"

[[entries]]
id = "62e53bc6-46fe-44ef-a7ed-6f91c8a8f11a"
type = "improvement"
description = "Add a `cargoDeny` task"
author = "trinquier.nico@gmail.com"
pr = "https://github.com/kraken-build/kraken-std/pull/118"
