[[entries]]
id = "fe19eb53-9dfc-482f-aa1c-5160e12fdf06"
type = "fix"
description = "properly rollback the Poetry project version after build"
author = "@Tpt"
pr = "https://github.com/kraken-build/kraken-std/pull/90"
