[[entries]]
id = "2ae9265f-3f77-4728-a902-b770927744c5"
type = "fix"
description = "Fix error when output directory does not exist for `dist()` when creating a Zip archive"
author = "@NiklasRosenstein"
