[[entries]]
id = "8906b2ba-d643-4e7c-8cb3-0a9fd993e912"
type = "fix"
description = "Compatibility of pyproject.toml with Poetry."
author = "@Tpt"
pr = "https://github.com/kraken-build/kraken-std/pull/100"

[[entries]]
id = "394bde18-7149-4e77-bfda-aa44569a0dcb"
type = "improvement"
description = "Enable `pytest --doctest-modules` flag (controlled by `PytestTask.doctest_modules`, enabled by default)."
author = "@NiklasRosenstein"
pr = "https://github.com/kraken-build/kraken-std/pull/101"

[[entries]]
id = "57c61a58-46f4-48d9-b111-f7f44bbfa142"
type = "improvement"
description = "Move task to check a valid readme exists from kraken-hs, and refactoring"
author = "@cdbrkfxrpt"
pr = "https://github.com/kraken-build/kraken-std/pull/103"
